### ISSUE TITLE
 requirement.txt

### ISSUE THREAD

**Issue by ghost** [giulio98/functional-diffusion-processes#2]
hi where is requirement.txt?

**Comment by giulio98** [comment]
Hello @cindyyyl 

Please, follow the steps outlined in the README.md to set up and run your virtual environment:

```
git clone git@github.com:giulio98/functional-diffusion-processes.git
cd functional-diffusion-processes
conda env create -f env.yaml
conda activate fdp
pip install -e .[dev]
pre-commit install
```

this will create and activate a virtual environment called `fdp` equipped with all required dependencies, if you are looking specifically for the versions of each package the file `env.yaml` contains a detailed listing of all dependencies.

Remember to create a  `.env` file with your secrets before you run any experiment.
```
nano .env
```
```
export WANDB_API_KEY=<your wandb api key>
export HOME=<your_home_directory>  # e.g., /home/username
export CUDA_HOME=/usr/local/cuda
export PROJECT_ROOT=<your_project_directory>  # /home/username/functional_diffusion_processes
export DATA_ROOT=${PROJECT_ROOT}/data
export LOGS_ROOT=${PROJECT_ROOT}/logs
export TFDS_DATA_DIR=${DATA_ROOT}/tensorflow_datasets
export PYTHONPATH=${PROJECT_ROOT}
export PYTHONUNBUFFERED=1
export HYDRA_FULL_ERROR=1
export WANDB_DISABLE_SERVICE=true
export CUDA_VISIBLE_DEVICES=<your cuda devices>
```

Please fill in the placeholders with your specific details.

**Comment by ghost** [comment]
Thank you so much !!!
