### ISSUE TITLE
No module named 'nn_core'

### ISSUE THREAD

**Issue by ghost** [giulio98/functional-diffusion-processes#3]
hi  i met some problem about nn_core.common in line  7 of run.py. could you please give me some instructions? Thank you!

(fdp) sh。。。。。/functional-diffusion-processes$ sh scripts/maml/train_mnist.sh
Traceback (most recent call last):
  File "src/functional_diffusion_processes/run.py", line 7, in <module>
    from nn_core.common import PROJECT_ROOT
ModuleNotFoundError: No module named 'nn_core'

**Comment by giulio98** [comment]
Hello, please follow the instructions in the ReadME to activate the environment and install all the dependences

```
git clone git@github.com:giulio98/functional-diffusion-processes.git
cd functional-diffusion-processes
conda env create -f env.yaml
conda activate fdp
pip install -e .[dev]
pre-commit install
```

specifically, I think you missed the command `pip install -e .[dev]`

does it resolve your issue?

**Comment by ghost** [comment]
That is great !  it be solved ! thank you so much !!
