### ISSUE TITLE
HI could you tell me where to upload checkpoint ?

### ISSUE THREAD

**Issue by ghost** [giulio98/functional-diffusion-processes#5]
HI could you tell me where to upload checkpoint ? 

thank you !!

**Comment by giulio98** [comment]
Hello!
You can download our pretrained checkpoints using gdown as written in the README
`pip install gdown
`
`
gdown --id 1R9aRsV7q4yU0ey47tR7hFvKttEilUv0i
unzip logs.zip
rm logs.zip
`

then run sampling for e.g in mnist by using our scripts

`
sh scripts/maml/sample_mnist.sh
`


If you want instead to use your custom checkpoint you have to change the save_dir: `${oc.env:LOGS_ROOT}/<your_checkpoint_directory>` in `conf/experiments_maml/exp_sampling_mnist.yaml`

Let me know if this resolved your issue.

Giulio

**Comment by ghost** [comment]
Thank you very much! It solved my problem! Thanks!
