### ISSUE TITLE
Running Experiments on Custom Datasets

### ISSUE THREAD

**Issue by Z-Jianxin** [giulio98/functional-diffusion-processes#7]
Hi,

Could you provide guidance on conducting experiments with custom datasets not included in TensorFlow's dataset collection? Your assistance is greatly appreciated.

Thanks,

**Comment by giulio98** [comment]
Hi! Thank you for your interest.

Maybe this guide https://www.tensorflow.org/datasets/add_dataset?hl=en can be useful to you to convert your custom dataset to tensorflow format.

Then the integration in our repository should be easy.
